### ISSUE TITLE
Weird behavior on adding bend to a multi-edge

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-edge-bend-editing#11]
@royludo:
When you have 2 edges between the same 2 nodes, and both edges haven't been touched (no bend point used), then when you want to add a bend point to one edge, they kind of merge and get locked together.

Weirder thing: if the distance between the 2 nodes is large, you can correctly edit the bend point and have a normal behavior IF you click and place your bend point very close to one of the node. When clicking in the middle of the edge to place the bend point, the weird behavior happens.

**Comment by vishaltanwar** [comment]
I am unable to save bending data along with elements.
var elements = cy.elements().jsons();
Is there any way to save and restore bending data?

**Comment by vishaltanwar** [comment]
Small enhancements needed.
1. Disable bending using config parameter.
2. Remove all bend points of an Edge.
3. Straighten line option on context menu (right click) will remove all bends of selected edge. (ref 2)

I am done with 2nd and 3rd but I am sure there can be better code. I am attaching file with changes.

[cytoscape-edge-bend-editing.zip](https://github.com/iVis-at-Bilkent/cytoscape.js-edge-bend-editing/files/830022/cytoscape-edge-bend-editing.zip)
