### ISSUE TITLE
Save / Restore / Render bending data

### ISSUE THREAD

**Issue by vishaltanwar** [iVis-at-Bilkent/cytoscape.js-edge-bend-editing#12]
I made changes to plug-in to save data into **edge.data**  instead **edge.scratch** and now i can save serialized bending data along with edge data and restore it later.

`var exported = cy.elements().jsons();`

but my issue is when i restore it by rendering again using same element data then it does not display bends. I have to personally click on edge then it shows bend, to prevent manual click I had to apply a workaround, which works but there should be a better way. 
```
cy.elements().each(function (i, ele) {
		if (ele.group() == "edges") {
			ele.select();
			ele.unselect();
		}
	});

```
_Can you add method for export, import and apply bend data?_
Attached file with changes. Search for vishal keyword in file to see changes.
[cytoscape-edge-bend-editing.zip](https://github.com/iVis-at-Bilkent/cytoscape.js-edge-bend-editing/files/833748/cytoscape-edge-bend-editing.zip)

**Comment by ugurdogrusoz** [comment]
@vishaltanwar any changes requested should be made in the form a pull-request. thanks

**Comment by vishaltanwar** [comment]
Can you please tell me a how to redraw an edge with bends. Need a function to which i pass edge and it redraws it. e.g. redrawWithBends(edge) assuming edge.data.bends has its bendpoints?

**Comment by ugurdogrusoz** [comment]
@metincansiper I don't know at what level this is / should be supported but I can currently persist bends in Newt. Is this issue obsolete?

**Comment by metincansiper** [comment]
@ugurdogrusoz In Newt we get bend points data of an edge using a method exposed in this extension and use that data upon save. 
@vishaltanwar we have a method called 'getSegmentPoints' to get bend points information of an edge. You can check it here 'https://github.com/iVis-at-Bilkent/cytoscape.js-edge-bend-editing#api'

**Comment by ugurdogrusoz** [comment]
I don't see an issue here; closing it
