### ISSUE TITLE
Unable to add bendpoints with initbendpoints

### ISSUE THREAD

**Issue by kunalganglani** [iVis-at-Bilkent/cytoscape.js-edge-bend-editing#14]
Hi 
I am unable to add bend points by init bend points. Trying to achieve something like that in the image added:
![screen shot 2017-10-31 at 5 06 27 pm](https://user-images.githubusercontent.com/16814533/32316002-65d37dc6-bfd4-11e7-8c0a-85ad85e4e05c.png)

But now able to achieve. Please help
http://plnkr.co/edit/Ry88ZxN6qt6pkjmkHDxx?p=preview

**Comment by kinimesi** [comment]
@kunalganglani you need to specify `bendPointPositions` as object. 
```js
bendPointPositions: [{x:500,y:225}, {x:500,y:675}]
```
You also did not include jquery which is required by the extension.

Check the demo here: http://plnkr.co/edit/3bZWk3RW877JNOM9PI4U?p=preview

**Comment by gs-kganglani** [comment]
is there a way to add these bend points dynamically, rather than specifying as the edge data,
also please let me know if i can lock the edges, to prevent user from bending the edge.

**Comment by kinimesi** [comment]
@kunalganglani @gs-kganglani you can use `bendPositionsFunction` option.
