### ISSUE TITLE
Option to lock edges with bend points, and creation of new bendpoint on edge

### ISSUE THREAD

**Issue by kunalganglani** [iVis-at-Bilkent/cytoscape.js-edge-bend-editing#15]
Hi Cytoscape Team,
Please let me know if there is a way i can lock the edges, which have bend points added to them. 
I want to lock: 
Movement of such edges, 
Creation of more bend point by users

If possible: please edit: http://plnkr.co/edit/3bZWk3RW877JNOM9PI4U?p=preview 
and share your version. 
Your help would be greatly appreciated

Best Regards,
Kunal Ganglani

**Comment by ugurdogrusoz** [comment]
@kunalganglani Which one of these are you trying to do:
1) Pre-determine bends of edges and do not allow the user to change them: in this case, do not use this extension since this extension is to enable modification of (add/delete/relocate) bend points.
2) Allow user to change bend points for a while and them disable editing of bends
3) Other: please clarify

**Comment by kunalganglani** [comment]
I want to achieve this: http://embed.plnkr.co/gGQYdhr7K0gpseM2appA/
But I dont want the user to modify the edge bends at all. 
The current output allows modification of edge bends. 
I tried to add an edge between nodes of a compound node, but the results (PFA image) are unsatisfactory. 

![screen shot 2017-11-30 at 7 13 07 pm](https://user-images.githubusercontent.com/16814533/33433695-9941cdfe-d602-11e7-9191-babfd65a6985.png)

Requirements: 
I want to lock edge, specifically the addition of bend points to the edge
I want this to have 2 nodes in a compound node to be linked to each other, but the connection coming from outside the compound node, and not like the image shown

Desired Output: 
![screen shot 2017-11-30 at 7 20 19 pm](https://user-images.githubusercontent.com/16814533/33433929-93b621e0-d603-11e7-9951-8435e1791c3a.png)

**Comment by kinimesi** [comment]
@kunalganglani The purpose of this extension is to enable **interactive** editing of edge bend points. If you do not want to let the user move/add bend points, then you should not use this extension. Instead you can use [Segment Edges](http://js.cytoscape.org/#style/segments-edges) See and example [here](http://js.cytoscape.org/demos/edge-types/)

**Comment by ugurdogrusoz** [comment]
Notice that Segment Edges are available in Cytoscape.js core; hence no need to use this or any other extension.
