### ISSUE TITLE
Exclude edges from edge-bend-editing

### ISSUE THREAD

**Issue by Flui** [iVis-at-Bilkent/cytoscape.js-edge-bend-editing#9]
If there is not already a posibility to exlude some edges from editing.
E.g. by adding a class to those edges who should be editable or add a class to those who don't.

**Comment by ugurdogrusoz** [comment]
See https://github.com/iVis-at-Bilkent/cytoscape.js-edge-bend-editing/pull/10

**Comment by metincansiper** [comment]
@ugurdogrusoz  I merged #10.
